services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: timescaledb
    environment:
      POSTGRES_DB: ${DB_NAME:-pumpdb}
      POSTGRES_USER: ${DB_USER:-pumpuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-pumpsecret}
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-pumpuser} -d ${DB_NAME:-pumpdb}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  entry:
    image: ${DOCKERHUB_USERNAME:-poctak}/pump-entry:${APP_TAG:-latest}
    build:
      context: ./entry_service
      dockerfile: Dockerfile
    container_name: pump_entry
    env_file: ./entry_service/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  exit:
    image: ${DOCKERHUB_USERNAME:-poctak}/pump-exit:${APP_TAG:-latest}
    build:
      context: ./exit_service
      dockerfile: Dockerfile
    container_name: pump_exit
    env_file: ./exit_service/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  volume_entry:
    image: ${DOCKERHUB_USERNAME:-poctak}/pump-volume_entry:${APP_TAG:-latest}
    build:
      context: ./volume_entry_service
      dockerfile: Dockerfile
    container_name: pump_volume_entry
    env_file:
      - ./volume_service/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped


  acumulation_entry:
    image: ${DOCKERHUB_USERNAME:-poctak}/accumulation_entry:${APP_TAG:-latest}
    build:
      context: ./acumulation_entry_service
      dockerfile: Dockerfile
    container_name: acumulation_entry
    env_file: ./acumulation_service/.env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
