name: Build & Deploy (tag)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # ----------------------
      # Build & push EXIT image
      # ----------------------
      - name: Build and push EXIT image
        uses: docker/build-push-action@v5
        with:
          context: ./exit_service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-exit:${{ steps.vars.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-exit:latest

      # -----------------------
      # Build & push ACCUMULATION_ENTRY image
      # -----------------------
      - name: Build and push ACCUMULATION_ENTRY image
        uses: docker/build-push-action@v5
        with:
          context: ./acumulation_entry_service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-acumulation_entry:${{ steps.vars.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-acumulation_entry:latest
      
      - name: Build and push order_executor image
        uses: docker/build-push-action@v5
        with:
          context: ./order_executor_service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-order_executor:${{ steps.vars.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-order_executor:latest

      - name: Build and push exit_executor image
        uses: docker/build-push-action@v5
        with:
          context: ./exit_executor_service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-exit_executor:${{ steps.vars.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-exit_executor:latest
            
      - name: Build and push data5m image
        uses: docker/build-push-action@v5
        with:
          context: ./data5m_service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-data5m:${{ steps.vars.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-data5m:latest
            

      # -------------
      # Deploy on server
      # -------------
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -euo pipefail
            cd ~/pump-app

            export APP_TAG='${{ steps.vars.outputs.TAG }}'
            export DOCKERHUB_USERNAME='${{ secrets.DOCKERHUB_USERNAME }}'
            export DOCKERHUB_TOKEN='${{ secrets.DOCKERHUB_TOKEN }}'

            # login is required for private repos
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            docker compose pull data5m # accumulation_entry order_executor exit exit_executor
            docker compose up -d --force-recreate data5m # accumulation_entry order_executor exit exit_executor

            docker image prune -f
