name: Build & Deploy (tag)

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag
        id: vars
        run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # -----------------------
      # Build & push ENTRY image
      # -----------------------
      - name: Build and push ENTRY image
        uses: docker/build-push-action@v5
        with:
          context: ./entry_service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-entry:${{ steps.vars.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-entry:latest

      # ----------------------
      # Build & push EXIT image
      # ----------------------
      - name: Build and push EXIT image
        uses: docker/build-push-action@v5
        with:
          context: ./exit_service
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-exit:${{ steps.vars.outputs.TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/pump-exit:latest

      # -------------
      # Deploy on server
      # -------------
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/pump-app

            export APP_TAG='${{ steps.vars.outputs.TAG }}'

            docker compose pull entry exit
            docker compose up -d --force-recreate entry exit
            docker image prune -f
